=== KCJamesWatts/li-armies/legions-imperialis-army-cards.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="army" type="armyType">
        <xs:key name="PKWeaponTrait">
            <xs:selector xpath="traits/trait" />
            <xs:field xpath="@name" />
        </xs:key>

        <xs:keyref name="FKWeaponTrait" refer="PKWeaponTrait">
            <xs:selector xpath="weapons/weapon/traits/trait" />
            <xs:field xpath="@name" />
        </xs:keyref>

        <xs:key name="PKWeapon">
            <xs:selector xpath="weapons/weapon" />
            <xs:field xpath="@name" />
        </xs:key>

        <xs:keyref name="FKUnitWeapon" refer="PKWeapon">
            <xs:selector xpath="units/unit/weapons/weapon" />
            <xs:field xpath="@name" />
        </xs:keyref>
    </xs:element>

    <xs:complexType name="armyType">
        <xs:sequence>
            <xs:element name="units" type="unitsType" />
            <xs:element name="weapons" type="weaponsType" />
            <xs:element name="formations" type="formationsType" />
            <xs:element name="traits" type="traitsType" />
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="unitType">
        <xs:sequence>
            <xs:element name="move" type="xs:string" />
            <xs:element name="save" type="xs:string" />
            <xs:element name="caf" type="xs:string" />
            <xs:element name="morale" type="xs:string" />
            <xs:element name="wounds" type="xs:string" />
            <xs:element name="weapons" type="unitWeaponsType" />
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="unitsType">
        <xs:sequence>
            <xs:element name="unit" type="unitType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="unitWeaponType">
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="unitWeaponsType">
        <xs:sequence>
            <xs:element name="weapon" type="unitWeaponType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="weaponType">
        <xs:sequence>
            <xs:element name="range" type="xs:string" />
            <xs:element name="dice" type="xs:string" />
            <xs:element name="tohit" type="xs:string" />
            <xs:element name="ap" type="xs:string" />
            <xs:element name="traits" type="weaponTraitsType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="weaponsType">
        <xs:sequence>
            <xs:element name="weapon" type="weaponType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="weaponTraitsType">
        <xs:sequence>
            <xs:element name="trait" type="weaponTraitType" maxOccurs="unbounded" /> 
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="weaponTraitType">
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="traitsType">
        <xs:sequence>
            <xs:element name="trait" type="traitType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="traitType">
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="detachmentType" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Air Support" />
            <xs:enumeration value="Artillery" />
            <xs:enumeration value="Bastion" />
            <xs:enumeration value="Battle Tank" />
            <xs:enumeration value="Core" />
            <xs:enumeration value="Heavy Armour" />
            <xs:enumeration value="HQ" />
            <xs:enumeration value="Knight" />
            <xs:enumeration value="Light Armour" />
            <xs:enumeration value="Support" />
            <xs:enumeration value="Titan" />
            <xs:enumeration value="Transport" />
            <xs:enumeration value="Vanguard" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="detachmentSlotType">
        <xs:attribute name="type" type="detachmentType" />
    </xs:complexType>

    <xs:complexType name="detachmentGroupType">
        <xs:sequence>
            <xs:element name="detachment" type="detachmentSlotType" maxOccurs="unbounded" />
            <xs:element name="detachmentChoice" type="detachmentGroupType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formationType">
        <xs:sequence>
            <xs:element name="compulsory" type="detachmentGroupType" />
            <xs:element name="optional" type="detachmentGroupType" />
            <xs:element name="rule" type="formationRule" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="formationsType">
        <xs:sequence>
            <xs:element name="formation" type="formationType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formationRule">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="detachments">
        <xs:sequence>
            <xs:element name="detachment" type="detachment" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="detachment">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="cost" type="xs:int" />
        <xs:attribute name="size" type="xs:int" />
        <xs:attribute name="unitType" type="xs:string" />
        <xs:attribute name="unitSize" type="xs:int" />
    </xs:complexType>
</xs:schema>

=== KCJamesWatts/li-armies/adeptus-astartes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE doc [
    <!ENTITY weapon-traits-file SYSTEM "weapon-traits.xml">
]>

<?xml-stylesheet type="text/xsl" href="army-list.xsl"?>

<army name="Adeptus Astartes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xsi:noNamespaceSchemaLocation="legions-imperialis-army-cards.xsd">

    <units>
        <unit name="Tactical Legionnaries">
            <move>5"</move>
            <save>5+</save>
            <caf>+2</caf>
            <morale>3+</morale>
            <wounds>1</wounds>
            <weapons>
                <weapon name="Bolter" />
            </weapons>
        </unit>

        <unit name="Missile Launcher Heavy Support Legionnaries">
            <move>5"</move>
            <save>5+</save>
            <caf>+2</caf>
            <morale>3+</morale>
            <wounds>1</wounds>
            <weapons>
                <weapon name="Missile Launcher (Frag)" />
                <weapon name="Missile Launcher (Krak)" />
            </weapons>
        </unit>

        <unit name="Plasma Tactical Support Legionnaries">
            <move>5"</move>
            <save>5+</save>
            <caf>+2</caf>
            <morale>3+</morale>
            <wounds>1</wounds>
            <weapons>
                <weapon name="Plasma Gun" />
            </weapons>
        </unit>

        <unit name="Assault Marines">
            <move>7"</move>
            <save>5+</save>
            <caf>+3</caf>
            <morale>3+</morale>
            <wounds>1</wounds>
            <weapons>
                <weapon name="Bolt Pistol" />
            </weapons>
        </unit>

        <unit name="Legion Terminators">
            <move>5"</move>
            <save>4+</save>
            <caf>+4</caf>
            <morale>3+</morale>
            <wounds>1</wounds>
            <weapons>
                <weapon name="Combi-Bolter" />
            </weapons>
        </unit>
    </units>

    <weapons>
        <weapon name="Bolter">
            <range>8"</range>
            <dice>1</dice>
            <tohit>5+</tohit>
            <ap>0</ap>
            <traits>
                <trait name="Assault" />
                <trait name="Light" />
            </traits>
        </weapon>

        <weapon name="Bolt Pistol">
            <range>6"</range>
            <dice>1</dice>
            <tohit>5+</tohit>
            <ap>0</ap>
            <traits>
                <trait name="Light" />
            </traits>
        </weapon>

        <weapon name="Combi-Bolter">
            <range>8"</range>
            <dice>1</dice>
            <tohit>5+</tohit>
            <ap>0</ap>
            <traits>
                <trait name="Accurate" />
                <trait name="Assault" />
                <trait name="Light" />
            </traits>
        </weapon>

        <weapon name="Missile Launcher (Frag)">
            <range>20"</range>
            <dice>2</dice>
            <tohit>4+</tohit>
            <ap>0</ap>
            <traits>
                <trait name="Ignores Cover" />
                <trait name="Light" />
            </traits>
        </weapon>

        <weapon name="Missile Launcher (Krak)">
            <range>20"</range>
            <dice>1</dice>
            <tohit>4+</tohit>
            <ap>-1</ap>
            <traits>
                <trait name="Anti-Tank" />
            </traits>
        </weapon>

        <weapon name="Plasma Gun">
            <range>10"</range>
            <dice>1</dice>
            <tohit>4+</tohit>
            <ap>-1</ap>
            <traits>
                <trait name="Light AT" />
            </traits>
        </weapon>
    </weapons>

    <formations>
        <formation name="Legion Ariel Assault">
            <compulsory>
                <detachment type="HQ" />
                <detachment type="Support" />
                <detachment type="Core" />
                <detachment type="Core" />
            </compulsory>

            <optional>
                <detachment type="Support" />
                <detachment type="Core" />
                <detachment type="Air Support" />
                <detachment type="Support" />
                <detachment type="Vanguard" />
                <detachment type="Air Support" />
            </optional>

            <rule name="Dedicated Transports">
                Any Legiones Astrates Detachment within a Legion Arial Assault Formation can be upgraded with Legion Storm Eagles
                or Legion Thunderhawks as Dedicated Transports, at a cost of +100 points per Storm Eagle and +150 points per
                Legion Thunderhawk.
            </rule>

            <rule name="Aerial Assault">
                All Detachments within the Formation that do not have the Flyer special rule must begin the game Embarked upon a Transport
                with the Flyer special rule.
            </rule>
        </formation>

        <formation name="Legion Armoured Company">
            <compulsory>
                <detachment type="Battle Tank" />
                <detachment type="Battle Tank" />
                <detachment type="Heavy Armour" />
            </compulsory>

            <optional>
                <detachment type="Light Armour" />
                <detachment type="Heavy Armour" />
                <detachment type="Battle Tank" />
                <detachment type="Battle Tank" />

                <detachmentChoice>
                    <detachment type="Air Support" />
                    <detachment type="Heavy Armour" />
                </detachmentChoice>
            </optional>
        </formation>

        <formation name="Legion Demi-Company">
            <compulsory>
                <detachment type="HQ" />
                <detachment type="Support" />
                <detachment type="Core" />
                <detachment type="Core" />
            </compulsory>

            <optional>
                <detachment type="Bastion" />
                <detachment type="Core" />
                <detachment type="Transport" />
                <detachment type="Transport" />
                <detachment type="Support" />
                <detachment type="Support" />
                <detachment type="Vanguard" />

                <detachmentChoice>
                    <detachment type="Light Armour" />
                    <detachment type="Air Support" />
                </detachmentChoice>

                <detachmentChoice>
                    <detachment type="Artillery" />
                    <detachment type="Battle Tank" />
                    <detachment type="Heavy Armour" />
                </detachmentChoice>
            </optional>

            <rule name="Dedicated Transports">
                Any Legiones Astrates Detachment within the Formation that contains only Infantry models may be
                upgraded with Legions Rhinos as Dedicated Transports.
            </rule>

            <rule name="Heart of the Legion">
                Compulsory Core Detachment slots in this formation must be filled with Legion Tactical Detachments.
                All non-infantry models within this formation increase their Tactical Strength by 1 when contesting
                an Objective marker that an infantry model within this Formation is also contesting.
            </rule>
        </formation>

        <formation name="Legion Garrison Force">
            <compulsory>
                <detachment type="HQ" />
                <detachment type="Support" />
                <detachment type="Core" />
                <detachment type="Bastion" />
            </compulsory>

            <optional>
                <detachment type="Bastion" />
                <detachment type="Core" />
                <detachment type="Air Support" />
                <detachment type="Bastion" />
                <detachment type="Support" />
                <detachment type="Support" />
                <detachment type="Artillery" />

                <detachmentChoice>
                    <detachment type="Heavy Armour" />
                    <detachment type="Artillery" />                    
                </detachmentChoice>
            </optional>
        </formation>
    </formations>

    <detachments>
        <detachment name="Legion Tactical Detachment" type="Core" cost="35" size="4" unitType="Infantry" unitSize="1">
            <unit name="Tactical Legionnaries" />

            <upgrades allowed="4">
                <upgrade cost="12" size="2" name="Tactical Legionnaries">
                    <unit name="Tactical Legionnaries" />
                </upgrade>

                <upgrade cost="15" size="2" name="Plasma Tactical Support Legionnaries">
                    <unit name="Plasma Tactical Support Legionnaries" />
                </upgrade>

                <upgrade cost="15" size="2" name="Missile Launcher Heavy Support Legionnaries">
                    <unit name="Missile Launcher Heavy Support Legionnaries" />
                </upgrade>

                <upgrade cost="15" size="2" name="Legion Terminators">
                    <unit name="Legion Terminators" />
                </upgrade>

                <upgrade cost="12" size="2" name="Assault Marines">
                    <unit name="Assault Marines" />
                </upgrade>
            </upgrades>
        </detachment>
    </detachments>

    &weapon-traits-file;
</army>
